name = "justeat-takeaway-web"
main = "_worker.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "build"

[site]
bucket = "./build"
entry-point = "."

[build.upload]
format = "service-worker" 